name: 'GitHub Actions '

on:
  push:
    branches: 
      - main
  schedule:
   - cron: '10 * * * *'
jobs:
  # This workflow contains a single job called "build"
  runs-on:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set time zone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "rm *txt"
          rm -rf *.txt
          echo $(date +%Y%m%d%H%M%S) > README.MD
          echo "下载tgip"
          curl https://zip.baipiao.eu.org -o tgip.zip
          unzip tgip.zip -d ./

      # Runs a set of commands using the runners shell
      - name: Commit files
        run: |
          git pull
          git config --local user.email "xd9722@gmail.com"
          git config --local user.name "x-dr"
          git add .
          git commit -m "⌚️$(date +%Y%m%d%H%M%S)" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          # github_token: ${{ secrets.GH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
